databases:
  - name: microverse-rails
    databaseName: microverse_rails
    user: microverse_rails_user

services:
  - type: web
    name: keenan-budget
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: microverse-rails
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false